# Generated by Django 3.2.6 on 2022-09-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api', models.CharField(choices=[('Sensibo', 'Sensibo'), ('Electra', 'Electra')], default='Sensibo', max_length=10)),
            ],
        ),
    ]
