# Generated by Django 3.2.6 on 2022-09-18 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_electraapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='electraapi',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 8, 44, 37, 10962, tzinfo=utc), verbose_name='timestamp'),
            preserve_default=False,
        ),
    ]
