# Generated by Django 3.2.6 on 2022-09-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_electraapi_ts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectraAPI',
        ),
    ]
