# Generated by Django 3.2.6 on 2022-09-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_electraapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_id', models.CharField(max_length=200)),
                ('api', models.CharField(choices=[('Ewelink', 'Ewelink')], default='Ewelink', max_length=10)),
            ],
        ),
    ]
