# Generated by Django 3.2.6 on 2022-10-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='api',
            field=models.CharField(choices=[('Ewelink', 'Ewelink'), ('Switcher', 'Switcher')], default='Ewelink', max_length=10),
        ),
    ]
