# Generated by Django 3.2.6 on 2022-10-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_switch_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='icon',
            field=models.CharField(choices=[('Bulb', 'Bulb'), ('Coffee', 'Coffee'), ('Shower', 'Shower')], default='Bulb', max_length=10),
        ),
    ]
