# Generated by Django 3.2.6 on 2022-10-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_switch_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='api',
            field=models.CharField(choices=[('Ewelink', 'Ewelink'), ('Switcher', 'Switcher'), ('Boiler', 'Boiler')], default='Ewelink', max_length=10),
        ),
    ]
