# Generated by Django 3.2.6 on 2022-10-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_action_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='actions',
        ),
        migrations.AddField(
            model_name='routine',
            name='actions',
            field=models.JSONField(default=[]),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
