# Generated by Django 3.2.6 on 2022-11-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.AddField(
            model_name='ac',
            name='fan',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], default='Low', max_length=5),
        ),
        migrations.AddField(
            model_name='ac',
            name='mode',
            field=models.CharField(choices=[('HEAT', 'Heat'), ('COOL', 'Cool'), ('FAN', 'Fan')], default='COOL', max_length=5),
        ),
        migrations.AddField(
            model_name='ac',
            name='power',
            field=models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=5),
        ),
        migrations.AddField(
            model_name='ac',
            name='temperature',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='switch',
            name='power',
            field=models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=5),
        ),
    ]
